Repository BBYUworld/gagyebbyu-be, pull requests merged in 2024-08, with the labels that each got.

#8 Feat/6 Expense CRUD 구현
  gagyebbyu/logs/spring-boot-application.log.2024-08-22.0.gz
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/controller/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/controller/ExpenseController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/param/ExpenseParam.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/request/ExpenseCreateDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/request/ExpenseMemoCreateDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/request/ExpenseTargetCreateDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/response/ExpenseOverviewDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/entity/Expense.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepositoryImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/ExpenseService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/controller/FundController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/entity/Fund.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/repository/FundRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/repository/FundTransactionRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/service/FundConditionService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/service/FundService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/dto/UserDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/entity/User.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/error/ErrorCode.java
Labels: Feat

#11 Feat/9 Expense API 추가
  gagyebbyu/.gitignore
  gagyebbyu/logs/spring-boot-application.log.2024-08-23.0.gz
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/entity/Couple.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/controller/ExpenseController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/param/ExpenseParam.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/request/ExpenseUpdateDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/response/ExpenseDayDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/response/ExpenseMonthDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/entity/Expense.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepositoryImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/ExpenseService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/service/FundService.java
Labels: Feat

#18 Feat/17 Couple 등록 API
  gagyebbyu/logs/spring-boot-application.log.2024-08-24.0.gz
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/controller/CoupleController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/dto/request/CoupleConnectDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/dto/request/CoupleCreateDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/entity/Couple.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/entity/Status.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/service/CoupleService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/entity/Expense.java
Labels: Feat, Refactor

#19 Feat/4 loan api 초안 작성
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/controller/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/controller/LoanController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/dto/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/dto/request/LoanRequestDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/dto/response/LoanResponseDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/entity/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/entity/Loan.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/entity/RatingName.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/repository/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/repository/LoanRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/service/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/service/LoanService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/service/LoanServiceImpl.java
Labels: Feat

#29 Feat/15 asset api 추가와 테스트 완료 병합
  .idea/.gitignore
  .idea/gagyebbyu-be.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  gagyebbyu/logs/spring-boot-application.log.2024-08-25.0.gz
  gagyebbyu/logs/spring-boot-application.log.2024-08-26.0.gz
  gagyebbyu/logs/spring-boot-application.log.2024-08-26.1.gz
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/AssetAccountController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/AssetCardController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/AssetController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/AssetLoanController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/dto/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/dto/AssetAccountDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/dto/AssetCardDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/dto/AssetDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/dto/AssetLoanDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/entity/Asset.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/entity/AssetAccount.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/entity/AssetCard.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/entity/AssetDeposit.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/entity/AssetLoan.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/entity/Type.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/enums/AccountType.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/enums/AssetType.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/enums/AssetTypeConverter.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/enums/CardType.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetAccountRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetCardRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetDepositRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetLoanRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/asset/AssetService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/asset/AssetServiceImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetAccount/AssetAccountService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetAccount/AssetAccountServiceImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetCard/AssetCardService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetCard/AssetCardServiceImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetLoan/AssetLoanService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetLoan/AssetLoanServiceImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/service/CoupleService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/controller/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/controller/LoanController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/dto/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/dto/response/LoanResponseDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/entity/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/repository/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/repository/LoanRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/service/.gitkeep
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/service/LoanService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/service/LoanServiceImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/service/AccountService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/service/UserService.java
  gagyebbyu/src/main/resources/application.yml
Labels: Feat, Merge into default

#31 Feat/27 Analysis Expense, Expense 조회
  gagyebbyu/logs/spring-boot-application.log.2024-08-26.0.gz
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/analysis/controller/AnalysisExpenseController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/analysis/dto/response/CoupleExpenseResultDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/analysis/service/CoupleExpenseService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/response/ExpenseMonthDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepositoryImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/ExpenseService.java
Labels: Feat, Refactor

#35 refactor: User entity 수정
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/dto/UserDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/entity/Occupation.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/entity/Region.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/entity/User.java
Labels: Refactor

#47 Fix/32 대출 총액 조회 api 추가
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/AssetController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/controller/AssetLoanController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetLoanRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/asset/AssetService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/asset/AssetServiceImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetLoan/AssetLoanService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/service/assetLoan/AssetLoanServiceImpl.java
Labels: Feat

#49 Feat/27 Expense 사용자 지출 연간 조회 api
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/controller/ExpenseController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepositoryImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/ExpenseService.java
Labels: Feat

#51 Refactor/27 Expense 월간 조회 수정
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/analysis/service/CoupleExpenseService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/response/ExpenseMonthDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseCustomRepositoryImpl.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/repository/ExpenseRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/ExpenseService.java
Labels: Refactor

#55 fix: Category 및 ExpenseDayDto 수정
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/dto/response/ExpenseDayDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/expense/service/ExpenseService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/service/AccountService.java
Labels: Fix

#60 Refactor/59 Recommend Deposit, Savings response 리팩토링
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/controller/RecommendController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/dto/response/DepositDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/dto/response/RecommendDepositDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/dto/response/RecommendSavingsDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/dto/response/SavingsDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/entity/Deposit.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/entity/Savings.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/repository/DepositRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/repository/SavingsRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/service/RecommendService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/error/ErrorCode.java
Labels: Refactor

#61 Hotfix/59 Recommend Loan Json 파싱 오류 해결
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/loan/dto/response/LoanResponseDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/controller/RecommendController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/dto/response/RecommendLoanDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/recommend/service/RecommendService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/webClient/service/ApiService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/error/ErrorCode.java
Labels: HotFix

#71 Fix/68 Fund 입/출금 API 수정
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/asset/repository/AssetAccountRepository.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/couple/service/CoupleService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/controller/FundController.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/dto/request/FundTransactionCreateDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/service/FundConditionService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/service/FundService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/user/service/AccountService.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/api/demanddeposit/DemandBalanceDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/api/demanddeposit/DepositDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/api/demanddeposit/WithdrawalDto.java
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/global/error/ErrorCode.java
Labels: Feat, Fix

#75 Hotfix/68 Fund 출금 에러코드 추가
  gagyebbyu/src/main/java/com/bbyuworld/gagyebbyu/domain/fund/service/FundService.java
Labels: HotFix
